name: Run Jupyter Notebooks

# this will run only modified notebook
# but could also run all notebooks on schedule with
# on:
#   push:
#     paths:
#       - "geometry/*.ipynb"
#   schedule:
#     - cron: "0 2 * * *"

on:
  push:
    paths:
      - "geometry/**/*.ipynb"
  pull_request:
    paths:
      - "geometry/**/*.ipynb"
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
      options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important for git diff

      - name: Execute notebooks and export to HTML
        shell: bash
        run: |
          mkdir -p reports
          for nb in geometry/*.ipynb; do
            echo "Running $nb"
            base=$(basename "$nb" .ipynb)
            jupyter nbconvert --to notebook --execute "$nb" --output "${base}_executed.ipynb"

            # Convert to HTML
            jupyter nbconvert --to html "${base}_executed.ipynb" --output "${base}.html"

            # Move HTML to reports folder
            mv "${base}.html" reports/
          done

      - name: Upload artifact (output)
        uses: actions/upload-artifact@v4
        with:
          name: notebook-html-reports
          path: reports/
